name = "passel"
description = ""
version = "0.1.0-dev"

authors = ["Tali Auster"]
maintainers = ["Tali Auster <me@tali.network>"]
maintainers-logins = ["atalii"]
licenses = "MPL-2.0"
website = ""
tags = []

[build-switches]

"*"."Ada_Version" = "Ada2022"
"*"."Contracts" = "Yes"

[[depends-on]]
ahtml = "~0.1.0-dev"
vss_extra = "26.2.0"

[[pins]]
ahtml = { url='https://github.com/atalii/ahtml', commit='e7d97e72dc81ec1cfbe9b0de118fa4992da439d1' }
